
   `undef AHB_DATA_WIDTH
   `undef APB_DATA_WIDTH
   `undef APB_DATA_WIDTH_32
   `undef APB_ENH_THROUGHPUT_EN
   `undef APB_HAS_APB3
   `undef APB_HAS_APB4
   `undef APB_HAS_S0
   `undef APB_HAS_S1
   `undef APB_HAS_XDCDR
   `undef APB_INTERFACE_TYPE_SLAVE_0
   `undef APB_INTERFACE_TYPE_SLAVE_1
   `undef APB_INTERFACE_TYPE_SLAVE_10
   `undef APB_INTERFACE_TYPE_SLAVE_11
   `undef APB_INTERFACE_TYPE_SLAVE_12
   `undef APB_INTERFACE_TYPE_SLAVE_13
   `undef APB_INTERFACE_TYPE_SLAVE_14
   `undef APB_INTERFACE_TYPE_SLAVE_15
   `undef APB_INTERFACE_TYPE_SLAVE_2
   `undef APB_INTERFACE_TYPE_SLAVE_3
   `undef APB_INTERFACE_TYPE_SLAVE_4
   `undef APB_INTERFACE_TYPE_SLAVE_5
   `undef APB_INTERFACE_TYPE_SLAVE_6
   `undef APB_INTERFACE_TYPE_SLAVE_7
   `undef APB_INTERFACE_TYPE_SLAVE_8
   `undef APB_INTERFACE_TYPE_SLAVE_9
   `undef APB_IS_APB3_0
   `undef APB_IS_APB3_1
   `undef APB_IS_APB3_10
   `undef APB_IS_APB3_11
   `undef APB_IS_APB3_12
   `undef APB_IS_APB3_13
   `undef APB_IS_APB3_14
   `undef APB_IS_APB3_15
   `undef APB_IS_APB3_2
   `undef APB_IS_APB3_3
   `undef APB_IS_APB3_4
   `undef APB_IS_APB3_5
   `undef APB_IS_APB3_6
   `undef APB_IS_APB3_7
   `undef APB_IS_APB3_8
   `undef APB_IS_APB3_9
   `undef BIG_ENDIAN
   `undef BUSY
   `undef BYTE
   `undef DWORD
   `undef END_PADDR_0
   `undef END_PADDR_1
   `undef END_PADDR_10
   `undef END_PADDR_11
   `undef END_PADDR_12
   `undef END_PADDR_13
   `undef END_PADDR_14
   `undef END_PADDR_15
   `undef END_PADDR_2
   `undef END_PADDR_3
   `undef END_PADDR_4
   `undef END_PADDR_5
   `undef END_PADDR_6
   `undef END_PADDR_7
   `undef END_PADDR_8
   `undef END_PADDR_9
   `undef ERROR
   `undef EXT_PROT_EN
   `undef FALSE
   `undef HADDR_SEL_WIDTH
   `undef HADDR_WIDTH
   `undef HADDR_WIDTH_INT
   `undef HBURST_WIDTH
   `undef HMASTER_WIDTH
   `undef HPROT_WIDTH
   `undef HRESP_WIDTH
   `undef HSIZE_WIDTH
   `undef HSPLIT_WIDTH
   `undef HTRANS_WIDTH
   `undef HWDATA32_WIDTH
   `undef HWORD
   `undef IDLE
   `undef INCR
   `undef INCR16
   `undef INCR4
   `undef INCR8
   `undef KBYTE
   `undef LWORD
   `undef MAX_AHB_DATA_WIDTH
   `undef MAX_APB_DATA_WIDTH
   `undef MAX_APB_SLAVES
   `undef MAX_PRDATABUS_WIDTH
   `undef NONSEQ
   `undef NUM_APB_SLAVES
   `undef OKAY
   `undef PADDR_SEL_WIDTH
   `undef PADDR_WIDTH
   `undef PRDATABUS_WIDTH
   `undef R0_APB_EA
   `undef R0_APB_SA
   `undef READ
   `undef RETRY
   `undef SEQ
   `undef SINGLE
   `undef SPLIT
   `undef START_PADDR_0
   `undef START_PADDR_1
   `undef START_PADDR_10
   `undef START_PADDR_11
   `undef START_PADDR_12
   `undef START_PADDR_13
   `undef START_PADDR_14
   `undef START_PADDR_15
   `undef START_PADDR_2
   `undef START_PADDR_3
   `undef START_PADDR_4
   `undef START_PADDR_5
   `undef START_PADDR_6
   `undef START_PADDR_7
   `undef START_PADDR_8
   `undef START_PADDR_9
   `undef TRUE
   `undef WORD
   `undef WORD16
   `undef WORD4
   `undef WORD8
   `undef WRAP16
   `undef WRAP4
   `undef WRAP8
   `undef WRITE
   `undef zero16
   `undef zero32
   `undef zero8
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
