
   `undef APB_DATA_WIDTH
   `undef GPIO_ADDR_SLICE_LHS
   `undef GPIO_ADDR_SLICE_RHS
   `undef GPIO_ADD_ENCODED_PARAMS
   `undef GPIO_CID_REG1
   `undef GPIO_CID_REG2
   `undef GPIO_CID_RESET_REG1
   `undef GPIO_CID_RESET_REG2
   `undef GPIO_COMBINED
   `undef GPIO_CONFIGID_REG1_OFFSET
   `undef GPIO_CONFIGID_REG2_OFFSET
   `undef GPIO_CTL_WIDTH_A
   `undef GPIO_CTL_WIDTH_B
   `undef GPIO_CTL_WIDTH_C
   `undef GPIO_CTL_WIDTH_D
   `undef GPIO_DEBOUNCE
   `undef GPIO_DFLT_DIR_A
   `undef GPIO_DFLT_DIR_B
   `undef GPIO_DFLT_DIR_C
   `undef GPIO_DFLT_DIR_D
   `undef GPIO_DFLT_SRC_A
   `undef GPIO_DFLT_SRC_B
   `undef GPIO_DFLT_SRC_C
   `undef GPIO_DFLT_SRC_D
   `undef GPIO_DFLT_SRC_RESET_A
   `undef GPIO_DFLT_SRC_RESET_B
   `undef GPIO_DFLT_SRC_RESET_C
   `undef GPIO_DFLT_SRC_RESET_D
   `undef GPIO_ENCODED_APB_WIDTH
   `undef GPIO_ENCODED_ID_WIDTH
   `undef GPIO_ENCODED_NUM_PORTS
   `undef GPIO_ENCODED_PWIDTH_A
   `undef GPIO_ENCODED_PWIDTH_B
   `undef GPIO_ENCODED_PWIDTH_C
   `undef GPIO_ENCODED_PWIDTH_D
   `undef GPIO_EXT_PORTA_OFFSET
   `undef GPIO_HW_PORTA
   `undef GPIO_HW_PORTB
   `undef GPIO_HW_PORTC
   `undef GPIO_HW_PORTD
   `undef GPIO_ID
   `undef GPIO_ID_CODE_OFFSET
   `undef GPIO_ID_NUM
   `undef GPIO_ID_WIDTH
   `undef GPIO_INDIVIDUAL
   `undef GPIO_INTEN_OFFSET
   `undef GPIO_INTMASK_OFFSET
   `undef GPIO_INTR_IO
   `undef GPIO_INTSTATUS_OFFSET
   `undef GPIO_INTTYPE_LEVEL_OFFSET
   `undef GPIO_INT_BOTH_EDGE
   `undef GPIO_INT_POL
   `undef GPIO_INT_POLARITY_OFFSET
   `undef GPIO_LS_SYNC_OFFSET
   `undef GPIO_LS_SYNC_WIDTH
   `undef GPIO_L_DEBOUNCE
   `undef GPIO_L_HW_PORTA
   `undef GPIO_L_HW_PORTB
   `undef GPIO_L_HW_PORTC
   `undef GPIO_L_HW_PORTD
   `undef GPIO_L_ID
   `undef GPIO_L_PORTA_INTR
   `undef GPIO_NUM_PORTS
   `undef GPIO_PA_SYNC_EXT_DATA
   `undef GPIO_PA_SYNC_INTERRUPTS
   `undef GPIO_PB_SYNC_EXT_DATA
   `undef GPIO_PC_SYNC_EXT_DATA
   `undef GPIO_PD_SYNC_EXT_DATA
   `undef GPIO_PORTA_EOI_OFFSET
   `undef GPIO_PORTA_INTR
   `undef GPIO_PORTA_SINGLE_CTL
   `undef GPIO_PORTB_SINGLE_CTL
   `undef GPIO_PORTC_SINGLE_CTL
   `undef GPIO_PORTD_SINGLE_CTL
   `undef GPIO_PORTX_READBACK_MUX
   `undef GPIO_PWIDTH_A
   `undef GPIO_PWIDTH_B
   `undef GPIO_PWIDTH_C
   `undef GPIO_PWIDTH_D
   `undef GPIO_RAW_INTSTATUS_OFFSET
   `undef GPIO_RDATA_WIDTH
   `undef GPIO_REV_ID
   `undef GPIO_REV_ID_NUM
   `undef GPIO_REV_ID_WIDTH
   `undef GPIO_SWPORTA_CTL_REG_SIZE
   `undef GPIO_SWPORTA_DDR_OFFSET
   `undef GPIO_SWPORTA_DR_OFFSET
   `undef GPIO_SWPORTA_RESET
   `undef GPIO_SWPORTB_CTL_REG_SIZE
   `undef GPIO_SWPORTB_RESET
   `undef GPIO_SWPORTC_CTL_REG_SIZE
   `undef GPIO_SWPORTC_RESET
   `undef GPIO_SWPORTD_CTL_REG_SIZE
   `undef GPIO_SWPORTD_RESET
   `undef GPIO_VERSION_ID
   `undef GPIO_VER_ID_CODE_OFFSET
   `undef MAX_APB_DATA_WIDTH
   `undef PORTA_INT_BOTHEDGE
   `undef PORTA_SINGLE_CTL
   `undef PORTB_SINGLE_CTL
   `undef PORTC_SINGLE_CTL
   `undef PORTD_SINGLE_CTL
   `undef POW_2_GPIO_ID_WIDTH
   `undef POW_2_GPIO_PWIDTH_A
   `undef POW_2_GPIO_PWIDTH_B
   `undef POW_2_GPIO_PWIDTH_C
   `undef POW_2_GPIO_PWIDTH_D
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
