
   `undef ADDITIONAL_FEATURES
   `undef AFCE_MODE
   `undef APB_DATA_WIDTH
   `undef BAUD_CLK
   `undef CLK_GATE_EN
   `undef CLOCK_MODE
   `undef CNT_WIDTH
   `undef DEBUG
   `undef DLF_SIZE
   `undef DLH_OFFSET
   `undef DLL_OFFSET
   `undef DMASA_OFFSET
   `undef DMA_EXTRA
   `undef DMA_HS_REQ_ON_RESET
   `undef DMA_IF_ACTIVE_HIGH
   `undef DMA_POL
   `undef FAR_OFFSET
   `undef FAR_RW
   `undef FCR_OFFSET
   `undef FIFO_ACCESS
   `undef FIFO_ADDR_WIDTH
   `undef FIFO_MODE
   `undef FIFO_MODE_ENABLED
   `undef FIFO_STAT
   `undef FRACTIONAL_BAUD_DIVISOR_EN
   `undef HAS_DMA_HS_REQ_ON_RESET
   `undef HTX_OFFSET
   `undef HTX_RW
   `undef IER_OFFSET
   `undef IIR_OFFSET
   `undef LATCH_MODE
   `undef LATCH_MODE_USER
   `undef LCR_OFFSET
   `undef LEGACY_RW
   `undef LPDLH_OFFSET
   `undef LPDLL_OFFSET
   `undef LSR_OFFSET
   `undef LSR_STATUS_CLEAR
   `undef MAX_APB_DATA_WIDTH
   `undef MCR_OFFSET
   `undef MCR_RW
   `undef MEM_MODE
   `undef MEM_MODE_USER
   `undef MEM_SELECT
   `undef MEM_SELECT_USER
   `undef MSR_OFFSET
   `undef PCLK_PER
   `undef RBR_OFFSET
   `undef RBR_RW
   `undef RFL_OFFSET
   `undef RFL_RW
   `undef RFW_OFFSET
   `undef RFW_RW
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA99
   `undef RTC_FCT
   `undef RXFIFO_RW
   `undef RX_RAM_DATA_WIDTH
   `undef SBCR_OFFSET
   `undef SBCR_RW
   `undef SCLK_PER
   `undef SCR_OFFSET
   `undef SDMAM_OFFSET
   `undef SDMAM_RW
   `undef SFE_OFFSET
   `undef SFE_RW
   `undef SHADOW
   `undef SIR_LP_MODE
   `undef SIR_LP_RX
   `undef SIR_MODE
   `undef SRBRN_REG_SIZE
   `undef SRBR_HIGH_OFFSET
   `undef SRBR_LOW_OFFSET
   `undef SRR_OFFSET
   `undef SRTS_OFFSET
   `undef SRTS_RW
   `undef SRT_OFFSET
   `undef SRT_RW
   `undef STET_OFFSET
   `undef STET_RW
   `undef STHRN_REG_SIZE
   `undef STHR_HIGH_OFFSET
   `undef STHR_LOW_OFFSET
   `undef TFL_OFFSET
   `undef TFL_RW
   `undef TFR_OFFSET
   `undef TFR_RW
   `undef THRE_MODE
   `undef THRE_MODE_RST
   `undef THRE_MODE_USER
   `undef THR_OFFSET
   `undef THR_RW
   `undef TO_DET_CNT_ENS_WIDTH
   `undef TXFIFO_RW
   `undef TX_RAM_DATA_WIDTH
   `undef UART_16550_COMPATIBLE
   `undef UART_9BIT_DATA_EN
   `undef UART_ADDR_SLICE_LHS
   `undef UART_ADD_ENCODED_PARAMS
   `undef UART_COMP_PARAM_RST
   `undef UART_COMP_TYPE
   `undef UART_COMP_VERSION
   `undef UART_CPR_OFFSET
   `undef UART_CTR_OFFSET
   `undef UART_CV_OFFSET
   `undef UART_DE_AT_RST
   `undef UART_DE_DAT_RST
   `undef UART_DE_POL
   `undef UART_DIV_WIDTH
   `undef UART_ENCODED_APB_WIDTH
   `undef UART_ENCODED_FIFO_MODE
   `undef UART_INCLUDE_LEGACY_BLOCK
   `undef UART_NUM_SAMPLES
   `undef UART_RE_POL
   `undef UART_RS485_INTERFACE_EN
   `undef UART_RS485_XFER_MODE_DFLT
   `undef UART_SIM_DO_SPECIAL_CONDITION
   `undef UART_SIM_FUNCTIONAL_COVERAGE
   `undef UART_SIM_MAX_ITERATION_VAL
   `undef UART_SIM_OVERRIDE
   `undef UART_SIM_OVERRIDE_DLH_VAL
   `undef UART_SIM_OVERRIDE_DLL_DLH
   `undef UART_SIM_OVERRIDE_DLL_VAL
   `undef UART_SIM_OVERRIDE_FCR
   `undef UART_SIM_OVERRIDE_FCR_DMAM_VAL
   `undef UART_SIM_OVERRIDE_FCR_FIFO_EN_VAL
   `undef UART_SIM_OVERRIDE_FCR_RT_VAL
   `undef UART_SIM_OVERRIDE_FCR_TET_VAL
   `undef UART_SIM_OVERRIDE_IER
   `undef UART_SIM_OVERRIDE_IER_EDSSI_VAL
   `undef UART_SIM_OVERRIDE_IER_ELSI_VAL
   `undef UART_SIM_OVERRIDE_IER_ERBFI_VAL
   `undef UART_SIM_OVERRIDE_IER_ETBEI_VAL
   `undef UART_SIM_OVERRIDE_IER_PTIME_VAL
   `undef UART_SIM_OVERRIDE_LCR
   `undef UART_SIM_OVERRIDE_LCR_BREAK_VAL
   `undef UART_SIM_OVERRIDE_LCR_DLS_VAL
   `undef UART_SIM_OVERRIDE_LCR_EPS_VAL
   `undef UART_SIM_OVERRIDE_LCR_PEN_VAL
   `undef UART_SIM_OVERRIDE_LCR_SP_VAL
   `undef UART_SIM_OVERRIDE_LCR_STOP_VAL
   `undef UART_SIM_OVERRIDE_MAX_ITERATION_VAL
   `undef UART_SIM_OVERRIDE_MAX_ROUND_VAL
   `undef UART_SIM_OVERRIDE_MCR
   `undef UART_SIM_OVERRIDE_MCR_AFCE_VAL
   `undef UART_SIM_OVERRIDE_MCR_LOOPBACK_VAL
   `undef UART_SIM_OVERRIDE_MCR_SIRE_VAL
   `undef UART_SIM_OVERRIDE_RX_BREAK_CHAR
   `undef UART_SIM_OVERRIDE_RX_ERROR
   `undef UART_SIM_OVERRIDE_RX_FRAMING_ERROR
   `undef UART_SIM_OVERRIDE_RX_PARITY_ERROR
   `undef UART_SIM_OVERRIDE_SIOTXRX_DRIVE_DCD_DSR_RI
   `undef UART_SIM_OVERRIDE_TRANSFER_DIRECTION_VAL
   `undef UART_SIM_RANDOM_SEED
   `undef UART_SIM_REPORT_DEBUG
   `undef UART_SIM_SCLK_PCLK_RELATIONSHIP
   `undef UART_SIM_SCLK_PERIOD
   `undef UART_SIM_SHORT_CHARACTER_STREAM_LENGTH
   `undef UART_SIM_SIOMON_ACTIVE_ON_SIN
   `undef UART_SIM_TERMINATE_ON_CHECKER_FAILURE
   `undef UART_SIM_TERMINATE_ON_SIOMON_ERROR
   `undef UART_SIM_USE_DIRECTED_CONTROL
   `undef UART_TAT_RST
   `undef UART_TCR_RST
   `undef UART_USE_ALT_DUT
   `undef USR_OFFSET
   `undef WIRE_SIN_TO_SIO
   `undef WR_DATA_WIDTH
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
