// This file was automatically generated by coreAssembler (version L-2016.09-SP1).
// 
// FILENAME : /root/Subsystem1/src/Subsystem1.v
// DATE : 06/04/18 11:36:59
// ABSTRACT : Verilog top-level subsystem RTL.
// 

module Subsystem1 (// Ports for Interface DW_apb_gpio-API
                   DW_apb_gpio_API_gpio_ext_porta,
                   DW_apb_gpio_API_gpio_porta_ddr,
                   DW_apb_gpio_API_gpio_porta_dr,
                   // Ports for Interface HCLK
                   HCLK_hclk,
                   // Ports for Interface HRESETn
                   HRESETn_hresetn,
                   // Ports for Interface PCLK
                   PCLK_pclk,
                   // Ports for Interface PRESETn
                   PRESETn_presetn,
                   // Ports for Interface SIO
                   SIO_cts_n,
                   SIO_sin,
                   SIO_rts_n,
                   SIO_sout,
                   // Ports for Interface ahb_mem
                   ahb_mem_hrdata,
                   ahb_mem_hready_resp,
                   ahb_mem_hresp,
                   ahb_mem_haddr,
                   ahb_mem_hburst,
                   ahb_mem_hmastlock,
                   ahb_mem_hprot,
                   ahb_mem_hready,
                   ahb_mem_hsel,
                   ahb_mem_hsize,
                   ahb_mem_htrans,
                   ahb_mem_hwdata,
                   ahb_mem_hwrite,
                   // Ports for Interface ahb_reg
                   ahb_reg_hrdata,
                   ahb_reg_hready_resp,
                   ahb_reg_hresp,
                   ahb_reg_haddr,
                   ahb_reg_hburst,
                   ahb_reg_hmastlock,
                   ahb_reg_hprot,
                   ahb_reg_hready,
                   ahb_reg_hsel,
                   ahb_reg_hsize,
                   ahb_reg_htrans,
                   ahb_reg_hwdata,
                   ahb_reg_hwrite,
                   // Ports for Interface d_port
                   d_port_haddr,
                   d_port_hburst,
                   d_port_hbusreq,
                   d_port_hlock,
                   d_port_hprot,
                   d_port_hsize,
                   d_port_htrans,
                   d_port_hwdata,
                   d_port_hwrite,
                   d_port_hgrant,
                   d_port_hrdata,
                   d_port_hready,
                   d_port_hresp,
                   // Ports for Interface i_port
                   i_port_haddr,
                   i_port_hburst,
                   i_port_hbusreq,
                   i_port_hlock,
                   i_port_hprot,
                   i_port_hsize,
                   i_port_htrans,
                   i_port_hwdata,
                   i_port_hwrite,
                   i_port_hgrant,
                   i_port_hrdata,
                   i_port_hready,
                   i_port_hresp,
                   // Ports for Manually exported pins
                   i_ahb_pause,
                   i_apb_pclk_en,
                   i_gpio_pclk_intr,
                   i_uart_dcd_n,
                   i_uart_dsr_n,
                   i_uart_ri_n,
                   i_uart_scan_mode,
                   i_ahb_hmaster_data,
                   i_gpio_gpio_intr_n,
                   i_gpio_gpio_intrclk_en,
                   i_uart_dma_rx_req,
                   i_uart_dma_tx_req,
                   i_uart_dtr_n,
                   i_uart_intr,
                   i_uart_out1_n,
                   i_uart_out2_n,
                   i_uart_rxrdy_n,
                   i_uart_txrdy_n
                   );

   // Ports for Interface DW_apb_gpio-API
   input  [7:0]   DW_apb_gpio_API_gpio_ext_porta;
   output [7:0]   DW_apb_gpio_API_gpio_porta_ddr;
   output [7:0]   DW_apb_gpio_API_gpio_porta_dr;
   // Ports for Interface HCLK
   input          HCLK_hclk;
   // Ports for Interface HRESETn
   input          HRESETn_hresetn;
   // Ports for Interface PCLK
   input          PCLK_pclk;
   // Ports for Interface PRESETn
   input          PRESETn_presetn;
   // Ports for Interface SIO
   input          SIO_cts_n;
   input          SIO_sin;
   output         SIO_rts_n;
   output         SIO_sout;
   // Ports for Interface ahb_mem
   input  [31:0]  ahb_mem_hrdata;
   input          ahb_mem_hready_resp;
   input  [1:0]   ahb_mem_hresp;
   output [31:0]  ahb_mem_haddr;
   output [2:0]   ahb_mem_hburst;
   output         ahb_mem_hmastlock;
   output [3:0]   ahb_mem_hprot;
   output         ahb_mem_hready;
   output         ahb_mem_hsel;
   output [2:0]   ahb_mem_hsize;
   output [1:0]   ahb_mem_htrans;
   output [31:0]  ahb_mem_hwdata;
   output         ahb_mem_hwrite;
   // Ports for Interface ahb_reg
   input  [31:0]  ahb_reg_hrdata;
   input          ahb_reg_hready_resp;
   input  [1:0]   ahb_reg_hresp;
   output [31:0]  ahb_reg_haddr;
   output [2:0]   ahb_reg_hburst;
   output         ahb_reg_hmastlock;
   output [3:0]   ahb_reg_hprot;
   output         ahb_reg_hready;
   output         ahb_reg_hsel;
   output [2:0]   ahb_reg_hsize;
   output [1:0]   ahb_reg_htrans;
   output [31:0]  ahb_reg_hwdata;
   output         ahb_reg_hwrite;
   // Ports for Interface d_port
   input  [31:0]  d_port_haddr;
   input  [2:0]   d_port_hburst;
   input          d_port_hbusreq;
   input          d_port_hlock;
   input  [3:0]   d_port_hprot;
   input  [2:0]   d_port_hsize;
   input  [1:0]   d_port_htrans;
   input  [31:0]  d_port_hwdata;
   input          d_port_hwrite;
   output         d_port_hgrant;
   output [31:0]  d_port_hrdata;
   output         d_port_hready;
   output [1:0]   d_port_hresp;
   // Ports for Interface i_port
   input  [31:0]  i_port_haddr;
   input  [2:0]   i_port_hburst;
   input          i_port_hbusreq;
   input          i_port_hlock;
   input  [3:0]   i_port_hprot;
   input  [2:0]   i_port_hsize;
   input  [1:0]   i_port_htrans;
   input  [31:0]  i_port_hwdata;
   input          i_port_hwrite;
   output         i_port_hgrant;
   output [31:0]  i_port_hrdata;
   output         i_port_hready;
   output [1:0]   i_port_hresp;
   // Ports for Manually exported pins
   input          i_ahb_pause;
   input          i_apb_pclk_en;
   input          i_gpio_pclk_intr;
   input          i_uart_dcd_n;
   input          i_uart_dsr_n;
   input          i_uart_ri_n;
   input          i_uart_scan_mode;
   output [3:0]   i_ahb_hmaster_data;
   output [7:0]   i_gpio_gpio_intr_n;
   output         i_gpio_gpio_intrclk_en;
   output         i_uart_dma_rx_req;
   output         i_uart_dma_tx_req;
   output         i_uart_dtr_n;
   output         i_uart_intr;
   output         i_uart_out1_n;
   output         i_uart_out2_n;
   output         i_uart_rxrdy_n;
   output         i_uart_txrdy_n;

   wire [31:0]  i_ahb_haddr;
   wire [2:0]   i_ahb_hburst;
   wire         i_ahb_hmastlock;
   wire [3:0]   i_ahb_hprot;
   wire [31:0]  i_ahb_hrdata;
   wire         i_ahb_hready;
   wire [1:0]   i_ahb_hresp;
   wire         i_ahb_hsel_s1;
   wire [2:0]   i_ahb_hsize;
   wire [1:0]   i_ahb_htrans;
   wire [31:0]  i_ahb_hwdata;
   wire         i_ahb_hwrite;
   wire [31:0]  i_apb_hrdata;
   wire         i_apb_hready_resp;
   wire [1:0]   i_apb_hresp;
   wire [31:0]  i_apb_paddr;
   wire         i_apb_penable;
   wire         i_apb_psel_s0;
   wire         i_apb_psel_s1;
   wire [31:0]  i_apb_pwdata;
   wire         i_apb_pwrite;
   wire [31:0]  i_gpio_prdata;
   wire [31:0]  i_uart_prdata;

   i_ahb_DW_ahb i_ahb
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .pause          (i_ahb_pause),
       .haddr_m1       (i_port_haddr),
       .hburst_m1      (i_port_hburst),
       .hbusreq_m1     (i_port_hbusreq),
       .hlock_m1       (i_port_hlock),
       .hprot_m1       (i_port_hprot),
       .hsize_m1       (i_port_hsize),
       .htrans_m1      (i_port_htrans),
       .hwdata_m1      (i_port_hwdata),
       .hwrite_m1      (i_port_hwrite),
       .hgrant_m1      (i_port_hgrant),
       .haddr_m2       (d_port_haddr),
       .hburst_m2      (d_port_hburst),
       .hbusreq_m2     (d_port_hbusreq),
       .hlock_m2       (d_port_hlock),
       .hprot_m2       (d_port_hprot),
       .hsize_m2       (d_port_hsize),
       .htrans_m2      (d_port_htrans),
       .hwdata_m2      (d_port_hwdata),
       .hwrite_m2      (d_port_hwrite),
       .hgrant_m2      (d_port_hgrant),
       .hsel_s1        (i_ahb_hsel_s1),
       .hready_resp_s1 (i_apb_hready_resp),
       .hresp_s1       (i_apb_hresp),
       .hrdata_s1      (i_apb_hrdata),
       .hsel_s2        (ahb_reg_hsel),
       .hready_resp_s2 (ahb_reg_hready_resp),
       .hresp_s2       (ahb_reg_hresp),
       .hrdata_s2      (ahb_reg_hrdata),
       .hsel_s3        (ahb_mem_hsel),
       .hready_resp_s3 (ahb_mem_hready_resp),
       .hresp_s3       (ahb_mem_hresp),
       .hrdata_s3      (ahb_mem_hrdata),
       .haddr          (i_ahb_haddr),
       .hburst         (i_ahb_hburst),
       .hprot          (i_ahb_hprot),
       .hsize          (i_ahb_hsize),
       .htrans         (i_ahb_htrans),
       .hwdata         (i_ahb_hwdata),
       .hwrite         (i_ahb_hwrite),
       .hready         (i_ahb_hready),
       .hresp          (i_ahb_hresp),
       .hrdata         (i_ahb_hrdata),
       .hmaster        (),
       .hmaster_data   (i_ahb_hmaster_data),
       .hmastlock      (i_ahb_hmastlock));

   i_apb_DW_apb i_apb
      (.hclk        (HCLK_hclk),
       .hresetn     (HRESETn_hresetn),
       .haddr       (i_ahb_haddr),
       .hready      (i_ahb_hready),
       .hsel        (i_ahb_hsel_s1),
       .htrans      (i_ahb_htrans),
       .hwrite      (i_ahb_hwrite),
       .hsize       (i_ahb_hsize),
       .hburst      (i_ahb_hburst),
       .hresp       (i_apb_hresp),
       .hready_resp (i_apb_hready_resp),
       .hwdata      (i_ahb_hwdata),
       .hrdata      (i_apb_hrdata),
       .pclk_en     (i_apb_pclk_en),
       .paddr       (i_apb_paddr),
       .penable     (i_apb_penable),
       .pwrite      (i_apb_pwrite),
       .psel_s1     (i_apb_psel_s1),
       .prdata_s1   (i_uart_prdata),
       .psel_s0     (i_apb_psel_s0),
       .prdata_s0   (i_gpio_prdata),
       .pwdata      (i_apb_pwdata));

   i_gpio_DW_apb_gpio i_gpio
      (.pclk            (PCLK_pclk),
       .pclk_intr       (i_gpio_pclk_intr),
       .presetn         (PRESETn_presetn),
       .penable         (i_apb_penable),
       .pwrite          (i_apb_pwrite),
       .pwdata          (i_apb_pwdata),
       .paddr           (i_apb_paddr[6:0]),
       .psel            (i_apb_psel_s0),
       .gpio_ext_porta  (DW_apb_gpio_API_gpio_ext_porta),
       .gpio_porta_dr   (DW_apb_gpio_API_gpio_porta_dr),
       .gpio_porta_ddr  (DW_apb_gpio_API_gpio_porta_ddr),
       .gpio_intr_n     (i_gpio_gpio_intr_n),
       .gpio_intrclk_en (i_gpio_gpio_intrclk_en),
       .prdata          (i_gpio_prdata));

   i_uart_DW_apb_uart i_uart
      (.pclk       (PCLK_pclk),
       .presetn    (PRESETn_presetn),
       .penable    (i_apb_penable),
       .pwrite     (i_apb_pwrite),
       .pwdata     (i_apb_pwdata),
       .paddr      (i_apb_paddr[7:0]),
       .psel       (i_apb_psel_s1),
       .scan_mode  (i_uart_scan_mode),
       .cts_n      (SIO_cts_n),
       .dsr_n      (i_uart_dsr_n),
       .dcd_n      (i_uart_dcd_n),
       .ri_n       (i_uart_ri_n),
       .sin        (SIO_sin),
       .prdata     (i_uart_prdata),
       .dtr_n      (i_uart_dtr_n),
       .rts_n      (SIO_rts_n),
       .out2_n     (i_uart_out2_n),
       .out1_n     (i_uart_out1_n),
       .dma_tx_req (i_uart_dma_tx_req),
       .dma_rx_req (i_uart_dma_rx_req),
       .txrdy_n    (i_uart_txrdy_n),
       .rxrdy_n    (i_uart_rxrdy_n),
       .sout       (SIO_sout),
       .intr       (i_uart_intr));

   assign ahb_mem_haddr     = i_ahb_haddr;
   assign ahb_mem_hburst    = i_ahb_hburst;
   assign ahb_mem_hmastlock = i_ahb_hmastlock;
   assign ahb_mem_hprot     = i_ahb_hprot;
   assign ahb_mem_hready    = i_ahb_hready;
   assign ahb_mem_hsize     = i_ahb_hsize;
   assign ahb_mem_htrans    = i_ahb_htrans;
   assign ahb_mem_hwdata    = i_ahb_hwdata;
   assign ahb_mem_hwrite    = i_ahb_hwrite;
   assign ahb_reg_haddr     = i_ahb_haddr;
   assign ahb_reg_hburst    = i_ahb_hburst;
   assign ahb_reg_hmastlock = i_ahb_hmastlock;
   assign ahb_reg_hprot     = i_ahb_hprot;
   assign ahb_reg_hready    = i_ahb_hready;
   assign ahb_reg_hsize     = i_ahb_hsize;
   assign ahb_reg_htrans    = i_ahb_htrans;
   assign ahb_reg_hwdata    = i_ahb_hwdata;
   assign ahb_reg_hwrite    = i_ahb_hwrite;
   assign d_port_hrdata     = i_ahb_hrdata;
   assign d_port_hready     = i_ahb_hready;
   assign d_port_hresp      = i_ahb_hresp;
   assign i_port_hrdata     = i_ahb_hrdata;
   assign i_port_hready     = i_ahb_hready;
   assign i_port_hresp      = i_ahb_hresp;

   // Note: i_apb_paddr[31:8] is open

endmodule
